parameters:
  - name: clientArtifactName
    type: string
    default: ""
  - name: serverArtifactName
    type: string
    default: ""
  - name: outputArtifactName
    type: string
    default: ""

jobs:
  - job: MergeArtifacts
    displayName: Merge Artifacts
    steps:
      - download: current
        displayName: Artifacts - Download client
        artifact: ${{ parameters.clientArtifactName }}
      - download: current
        displayName: Artifacts - Download server
        artifact: ${{ parameters.serverArtifactName }}
      - task: ExtractFiles@1
        displayName: Artifacts - Extract Server artifact
        inputs:
          archiveFilePatterns: $(Pipeline.Workspace)/${{ parameters.serverArtifactName }}/${{ parameters.serverArtifactName }}.zip
          destinationFolder: WebApi
          cleanDestinationFolder: true
          overwriteExistingFiles: false
      - task: CopyFiles@2
        displayName: Artifacts - Include Client in wwwroot of Server
        inputs:
          SourceFolder: $(Pipeline.Workspace)/${{ parameters.clientArtifactName }}
          TargetFolder: WebApi/wwwroot
          CleanTargetFolder: false
      - task: ArchiveFiles@2
        displayName: Artifacts - Create new artifact
        inputs:
          rootFolderOrFile: WebApi
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Pipeline.Workspace)/${{parameters.outputArtifactName}}.zip
          replaceExistingArchive: true
      - publish: $(Pipeline.Workspace)/${{ parameters.outputArtifactName }}.zip
        displayName: Artifacts - Publish ${{ parameters.outputArtifactName }}
        artifact: ${{ parameters.outputArtifactName }}
